program: fine_tune_mosi.py
method: bayes
metric:
  name: test_mae
  goal: minimize
parameters:
  learning_rate:
    min: 0.00001
    max: 0.0001
  warmup_proportion:
    min: 0.05
    max: 0.25
  num_epochs:
    values:
    - 3
    - 4
    - 5
    - 6
  batch_size:
    - 8
    - 16
  max_text_length:
    min: 60
    max: 80
  max_time:
    min: 25
    max: 35

  