program: fine_tune_mosi.py
method: grid
metric:
  name: test_mae
  goal: minimize
parameters:
  learning_rate:
    values:
    - 0.0001
    - 0.00005
    - 0.00002
    - 0.00001
  warmup_proportion:
    values:
    - 0.1
    - 0.2
    - 0.3